# **Model Development and Offline Evaluation**

## **1. Data Preparation**

In [25]:
# Import the libraries

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score

In [2]:
# Load the dataset

wine_data = pd.read_csv("winequality-red.csv", sep=";")

wine_data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [3]:
wine_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB

In [4]:
wine_data.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [5]:
# Define quality class

def quality_class(score):
    if score <= 4:
        return 0
    elif score <= 6:
        return 1
    else:
        return 2

wine_data["quality_class"] = wine_data["quality"].apply(quality_class)

In [6]:
wine_data["quality_class"].value_counts().sort_index()

quality_class
0      63
1    1319
2     217
Name: count, dtype: int64

In [ ]:
# Identify features and target

X = wine_data.drop(columns=["quality", "quality_class"])
y = wine_data["quality_class"]

In [9]:
# Split data into train and test sets

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y)

print("Training:", X_train.shape)
print("Testing:", X_test.shape)

Training: (1279, 11)
Testing: (320, 11)

In [11]:
# Standardize the dataset using StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

## **2. Model Training and Evaluation**

In [15]:
# Train the Logistic Regression

log_model = LogisticRegression(max_iter=1000, random_state=42)

log_model.fit(X_train_scaled, y_train)

# Predict test data
y_pred_log = log_model.predict(X_test_scaled)

In [ ]:
# Train the Random Forest

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42)

rf_model.fit(X_train_scaled, y_train)

# Predict test data
y_pred_rf = rf_model.predict(X_test_scaled)

In [19]:
# Evaluate Accuracy and F1-score

# Logistic Regression

log_accuracy = accuracy_score(y_test, y_pred_log)
log_f1 = f1_score(y_test, y_pred_log, average="macro")

# Random Forest

rf_accuracy = accuracy_score(y_test, y_pred_rf)
rf_f1 = f1_score(y_test, y_pred_rf, average="macro")

print("Logistic Regression")
print("Accuracy:", log_accuracy)
print("F1-score:", log_f1)

print("\nRandom Forest")
print("Accuracy:", rf_accuracy)
print("F1-score:", rf_f1)

Logistic Regression
Accuracy: 0.84375
F1-score: 0.46763265911675983

Random Forest
Accuracy: 0.884375
F1-score: 0.5441194393662401

## **3. Model Comparison and Discussion**

In [20]:
# Model comparison

comparison = pd.DataFrame({
    "Model": ["Logistic Regression", "Random Forest"],
    "Accuracy": [log_accuracy, rf_accuracy],
    "F1-score": [log_f1, rf_f1]})

comparison

                 Model  Accuracy  F1-score
0  Logistic Regression  0.843750  0.467633
1        Random Forest  0.884375  0.544119

### **Insight**:

Random Forest performed better than Logistic Regression, achieving a higher accuracy (88.4% vs. 84.4%) and F1-score (54.4% vs. 46.8%). Random Forest was better able to capture the complex and nonlinear relationships between the wine characteristics and quality classes. However, An accuracy of 88.4% looks strong, but an F1 of 54.4% indicates that performance is not equally strong across the three quality classes, potentially due to class imbalance.

In [30]:
import sys
!{sys.executable} -m pip install flaml

Collecting flaml
  Downloading flaml-2.7.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: NumPy>=1.17 in c:\users\yvesa\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from flaml) (2.5.2)
Downloading flaml-2.7.0-py3-none-any.whl (352 kB)
Installing collected packages: flaml
Successfully installed flaml-2.7.0

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [36]:
import flaml
print("FLAML installed successfully")

FLAML installed successfully

In [38]:
# Run AutoML

from flaml import AutoML

automl = AutoML()

automl.fit(
    X_train=X_train_scaled,
    y_train=y_train,
    task="classification",
    metric="macro_f1",
    time_budget=60,
    estimator_list=["rf", "extra_tree"])

[flaml.automl.logger: 10-03 22:44:04] {2470} INFO - task = classification
[flaml.automl.logger: 10-03 22:44:04] {2481} INFO - Evaluation method: cv
[flaml.automl.logger: 10-03 22:44:04] {2584} INFO - Minimizing error metric: 1-macro_f1
[flaml.automl.logger: 10-03 22:44:04] {2701} INFO - List of ML learners in AutoML Run: ['rf', 'extra_tree']
[flaml.automl.logger: 10-03 22:44:04] {3006} INFO - iteration 0, current learner rf
[flaml.automl.logger: 10-03 22:44:04] {3141} INFO - Estimated sufficient time budget=1816s. Estimated necessary time budget=2s.
[flaml.automl.logger: 10-03 22:44:04] {3192} INFO -  at 0.2s,	estimator rf's best error=6.9866e-01,	best estimator rf's best error=6.9866e-01
[flaml.automl.logger: 10-03 22:44:04] {3006} INFO - iteration 1, current learner extra_tree
[flaml.automl.logger: 10-03 22:44:04] {3192} INFO -  at 0.4s,	estimator extra_tree's best error=6.9866e-01,	best estimator rf's best error=6.9866e-01
[flaml.automl.logger: 10-03 22:44:04] {3006} INFO - iteration 2, current learner rf
[flaml.automl.logger: 10-03 22:44:04] {3192} INFO -  at 0.6s,	estimator rf's best error=6.1420e-01,	best estimator rf's best error=6.1420e-01
[flaml.automl.logger: 10-03 22:44:04] {3006} INFO - iteration 3, current learner extra_tree
[flaml.automl.logger: 10-03 22:44:05] {3192} INFO -  at 0.8s,	estimator extra_tree's best error=6.9866e-01,	best estimator rf's best error=6.1420e-01
[flaml.automl.logger: 10-03 22:44:05] {3006} INFO - iteration 4, current learner rf
[flaml.automl.logger: 10-03 22:44:05] {3192} INFO -  at 0.9s,	estimator rf's best error=6.1420e-01,	best estimator rf's best error=6.1420e-01
[flaml.automl.logger: 10-03 22:44:05] {3006} INFO - iteration 5, current learner rf
[flaml.automl.logger: 10-03 22:44:05] {3192} INFO -  at 1.2s,	estimator rf's best error=6.1420e-01,	best estimator rf's best error=6.1420e-01
[flaml.automl.logger: 10-03 22:44:05] {3006} INFO - iteration 6, current learner rf
[flaml.automl.logger: 10-03 22:44:05] {3192} INFO -  at 1.3s,	estimator rf's best error=5.6902e-01,	best estimator rf's best error=5.6902e-01
[flaml.automl.logger: 10-03 22:44:05] {3006} INFO - iteration 7, current learner rf
[flaml.automl.logger: 10-03 22:44:05] {3192} INFO -  at 1.5s,	estimator rf's best error=5.6902e-01,	best estimator rf's best error=5.6902e-01
[flaml.automl.logger: 10-03 22:44:05] {3006} INFO - iteration 8, current learner rf
[flaml.automl.logger: 10-03 22:44:05] {3192} INFO -  at 1.7s,	estimator rf's best error=5.6902e-01,	best estimator rf's best error=5.6902e-01
[flaml.automl.logger: 10-03 22:44:05] {3006} INFO - iteration 9, current learner extra_tree
[flaml.automl.logger: 10-03 22:44:06] {3192} INFO -  at 1.9s,	estimator extra_tree's best error=6.9866e-01,	best estimator rf's best error=5.6902e-01
[flaml.automl.logger: 10-03 22:44:06] {3006} INFO - iteration 10, current learner extra_tree
[flaml.automl.logger: 10-03 22:44:06] {3192} INFO -  at 2.1s,	estimator extra_tree's best error=6.9866e-01,	best estimator rf's best error=5.6902e-01
[flaml.automl.logger: 10-03 22:44:06] {3006} INFO - iteration 11, current learner extra_tree
[flaml.automl.logger: 10-03 22:44:06] {3192} INFO -  at 2.2s,	estimator extra_tree's best error=6.9866e-01,	best estimator rf's best error=5.6902e-01
[flaml.automl.logger: 10-03 22:44:06] {3006} INFO - iteration 12, current learner rf
[flaml.automl.logger: 10-03 22:44:06] {3192} INFO -  at 2.5s,	estimator rf's best error=5.6902e-01,	best estimator rf's best error=5.6902e-01
[flaml.automl.logger: 10-03 22:44:06] {3006} INFO - iteration 13, current learner extra_tree
[flaml.automl.logger: 10-03 22:44:06] {3192} INFO -  at 2.7s,	estimator extra_tree's best error=6.9866e-01,	best estimator rf's best error=5.6902e-01
[flaml.automl.logger: 10-03 22:44:06] {3006} INFO - iteration 14, current learner rf
[flaml.automl.logger: 10-03 22:44:07] {3192} INFO -  at 2.9s,	estimator rf's best error=5.6902e-01,	best estimator rf's best error=5.6902e-01
[flaml.automl.logger: 10-03 22:44:07] {3006} INFO - iteration 15, current learner extra_tree
[flaml.automl.logger: 10-03 22:44:07] {3192} INFO -  at 3.0s,	estimator extra_tree's best error=6.9866e-01,	best estimator rf's best error=5.6902e-01
[flaml.automl.logger: 10-03 22:44:07] {3006} INFO - iteration 16, current learner rf
[flaml.automl.logger: 10-03 22:44:07] {3192} INFO -  at 3.3s,	estimator rf's best error=5.6902e-01,	best estimator rf's best error=5.6902e-01
[flaml.automl.logger: 10-03 22:44:07] {3006} INFO - iteration 17, current learner extra_tree
[flaml.automl.logger: 10-03 22:44:07] {3192} INFO -  at 3.6s,	estimator extra_tree's best error=6.9866e-01,	best estimator rf's best error=5.6902e-01
[flaml.automl.logger: 10-03 22:44:07] {3006} INFO - iteration 18, current learner rf
[flaml.automl.logger: 10-03 22:44:08] {3192} INFO -  at 3.8s,	estimator rf's best error=5.1630e-01,	best estimator rf's best error=5.1630e-01
[flaml.automl.logger: 10-03 22:44:08] {3006} INFO - iteration 19, current learner extra_tree
[flaml.automl.logger: 10-03 22:44:08] {3192} INFO -  at 4.0s,	estimator extra_tree's best error=6.9866e-01,	best estimator rf's best error=5.1630e-01
[flaml.automl.logger: 10-03 22:44:08] {3006} INFO - iteration 20, current learner rf
[flaml.automl.logger: 10-03 22:44:08] {3192} INFO -  at 4.2s,	estimator rf's best error=5.1630e-01,	best estimator rf's best error=5.1630e-01
[flaml.automl.logger: 10-03 22:44:08] {3006} INFO - iteration 21, current learner rf
[flaml.automl.logger: 10-03 22:44:08] {3192} INFO -  at 4.5s,	estimator rf's best error=5.1616e-01,	best estimator rf's best error=5.1616e-01
[flaml.automl.logger: 10-03 22:44:08] {3006} INFO - iteration 22, current learner extra_tree
[flaml.automl.logger: 10-03 22:44:09] {3192} INFO -  at 4.7s,	estimator extra_tree's best error=6.9866e-01,	best estimator rf's best error=5.1616e-01
[flaml.automl.logger: 10-03 22:44:09] {3006} INFO - iteration 23, current learner extra_tree
[flaml.automl.logger: 10-03 22:44:09] {3192} INFO -  at 5.0s,	estimator extra_tree's best error=6.9156e-01,	best estimator rf's best error=5.1616e-01
[flaml.automl.logger: 10-03 22:44:09] {3006} INFO - iteration 24, current learner rf
[flaml.automl.logger: 10-03 22:44:09] {3192} INFO -  at 5.2s,	estimator rf's best error=5.1616e-01,	best estimator rf's best error=5.1616e-01
[flaml.automl.logger: 10-03 22:44:09] {3006} INFO - iteration 25, current learner rf
[flaml.automl.logger: 10-03 22:44:09] {3192} INFO -  at 5.5s,	estimator rf's best error=5.1616e-01,	best estimator rf's best error=5.1616e-01
[flaml.automl.logger: 10-03 22:44:09] {3006} INFO - iteration 26, current learner rf
[flaml.automl.logger: 10-03 22:44:10] {3192} INFO -  at 5.8s,	estimator rf's best error=4.6881e-01,	best estimator rf's best error=4.6881e-01
[flaml.automl.logger: 10-03 22:44:10] {3006} INFO - iteration 27, current learner rf
[flaml.automl.logger: 10-03 22:44:10] {3192} INFO -  at 6.1s,	estimator rf's best error=4.6881e-01,	best estimator rf's best error=4.6881e-01
[flaml.automl.logger: 10-03 22:44:10] {3006} INFO - iteration 28, current learner rf
[flaml.automl.logger: 10-03 22:44:10] {3192} INFO -  at 6.3s,	estimator rf's best error=4.6574e-01,	best estimator rf's best error=4.6574e-01
[flaml.automl.logger: 10-03 22:44:10] {3006} INFO - iteration 29, current learner rf
[flaml.automl.logger: 10-03 22:44:10] {3192} INFO -  at 6.6s,	estimator rf's best error=4.6574e-01,	best estimator rf's best error=4.6574e-01
[flaml.automl.logger: 10-03 22:44:10] {3006} INFO - iteration 30, current learner rf
[flaml.automl.logger: 10-03 22:44:11] {3192} INFO -  at 6.8s,	estimator rf's best error=4.6574e-01,	best estimator rf's best error=4.6574e-01
[flaml.automl.logger: 10-03 22:44:11] {3006} INFO - iteration 31, current learner rf
[flaml.automl.logger: 10-03 22:44:11] {3192} INFO -  at 7.0s,	estimator rf's best error=4.6574e-01,	best estimator rf's best error=4.6574e-01
[flaml.automl.logger: 10-03 22:44:11] {3006} INFO - iteration 32, current learner rf
[flaml.automl.logger: 10-03 22:44:11] {3192} INFO -  at 7.3s,	estimator rf's best error=4.6574e-01,	best estimator rf's best error=4.6574e-01
[flaml.automl.logger: 10-03 22:44:11] {3006} INFO - iteration 33, current learner rf
[flaml.automl.logger: 10-03 22:44:11] {3192} INFO -  at 7.5s,	estimator rf's best error=4.6574e-01,	best estimator rf's best error=4.6574e-01
[flaml.automl.logger: 10-03 22:44:11] {3006} INFO - iteration 34, current learner rf
[flaml.automl.logger: 10-03 22:44:12] {3192} INFO -  at 7.8s,	estimator rf's best error=4.6574e-01,	best estimator rf's best error=4.6574e-01
[flaml.automl.logger: 10-03 22:44:12] {3006} INFO - iteration 35, current learner rf
[flaml.automl.logger: 10-03 22:44:12] {3192} INFO -  at 8.0s,	estimator rf's best error=4.6574e-01,	best estimator rf's best error=4.6574e-01
[flaml.automl.logger: 10-03 22:44:12] {3006} INFO - iteration 36, current learner rf
[flaml.automl.logger: 10-03 22:44:12] {3192} INFO -  at 8.1s,	estimator rf's best error=4.6574e-01,	best estimator rf's best error=4.6574e-01
[flaml.automl.logger: 10-03 22:44:12] {3006} INFO - iteration 37, current learner rf
[flaml.automl.logger: 10-03 22:44:12] {3192} INFO -  at 8.4s,	estimator rf's best error=4.5687e-01,	best estimator rf's best error=4.5687e-01
[flaml.automl.logger: 10-03 22:44:12] {3006} INFO - iteration 38, current learner rf
[flaml.automl.logger: 10-03 22:44:12] {3192} INFO -  at 8.6s,	estimator rf's best error=4.5687e-01,	best estimator rf's best error=4.5687e-01
[flaml.automl.logger: 10-03 22:44:12] {3006} INFO - iteration 39, current learner rf
[flaml.automl.logger: 10-03 22:44:13] {3192} INFO -  at 8.8s,	estimator rf's best error=4.5687e-01,	best estimator rf's best error=4.5687e-01
[flaml.automl.logger: 10-03 22:44:13] {3006} INFO - iteration 40, current learner rf
[flaml.automl.logger: 10-03 22:44:13] {3192} INFO -  at 9.0s,	estimator rf's best error=4.4912e-01,	best estimator rf's best error=4.4912e-01
[flaml.automl.logger: 10-03 22:44:13] {3006} INFO - iteration 41, current learner rf
[flaml.automl.logger: 10-03 22:44:13] {3192} INFO -  at 9.2s,	estimator rf's best error=4.4912e-01,	best estimator rf's best error=4.4912e-01
[flaml.automl.logger: 10-03 22:44:13] {3006} INFO - iteration 42, current learner rf
[flaml.automl.logger: 10-03 22:44:13] {3192} INFO -  at 9.5s,	estimator rf's best error=4.0882e-01,	best estimator rf's best error=4.0882e-01
[flaml.automl.logger: 10-03 22:44:13] {3006} INFO - iteration 43, current learner rf
[flaml.automl.logger: 10-03 22:44:13] {3192} INFO -  at 9.7s,	estimator rf's best error=4.0882e-01,	best estimator rf's best error=4.0882e-01
[flaml.automl.logger: 10-03 22:44:13] {3006} INFO - iteration 44, current learner rf
[flaml.automl.logger: 10-03 22:44:14] {3192} INFO -  at 9.9s,	estimator rf's best error=4.0882e-01,	best estimator rf's best error=4.0882e-01
[flaml.automl.logger: 10-03 22:44:14] {3006} INFO - iteration 45, current learner rf
[flaml.automl.logger: 10-03 22:44:14] {3192} INFO -  at 10.1s,	estimator rf's best error=4.0882e-01,	best estimator rf's best error=4.0882e-01
[flaml.automl.logger: 10-03 22:44:14] {3006} INFO - iteration 46, current learner rf
[flaml.automl.logger: 10-03 22:44:14] {3192} INFO -  at 10.5s,	estimator rf's best error=4.0882e-01,	best estimator rf's best error=4.0882e-01
[flaml.automl.logger: 10-03 22:44:14] {3006} INFO - iteration 47, current learner rf
[flaml.automl.logger: 10-03 22:44:14] {3192} INFO -  at 10.7s,	estimator rf's best error=4.0882e-01,	best estimator rf's best error=4.0882e-01
[flaml.automl.logger: 10-03 22:44:14] {3006} INFO - iteration 48, current learner rf
[flaml.automl.logger: 10-03 22:44:15] {3192} INFO -  at 10.9s,	estimator rf's best error=4.0882e-01,	best estimator rf's best error=4.0882e-01
[flaml.automl.logger: 10-03 22:44:15] {3006} INFO - iteration 49, current learner rf
[flaml.automl.logger: 10-03 22:44:15] {3192} INFO -  at 11.2s,	estimator rf's best error=4.0882e-01,	best estimator rf's best error=4.0882e-01
[flaml.automl.logger: 10-03 22:44:15] {3006} INFO - iteration 50, current learner rf
[flaml.automl.logger: 10-03 22:44:15] {3192} INFO -  at 11.6s,	estimator rf's best error=4.0882e-01,	best estimator rf's best error=4.0882e-01
[flaml.automl.logger: 10-03 22:44:15] {3006} INFO - iteration 51, current learner rf
[flaml.automl.logger: 10-03 22:44:16] {3192} INFO -  at 11.8s,	estimator rf's best error=4.0882e-01,	best estimator rf's best error=4.0882e-01
[flaml.automl.logger: 10-03 22:44:16] {3006} INFO - iteration 52, current learner rf
[flaml.automl.logger: 10-03 22:44:16] {3192} INFO -  at 12.0s,	estimator rf's best error=4.0882e-01,	best estimator rf's best error=4.0882e-01
[flaml.automl.logger: 10-03 22:44:16] {3006} INFO - iteration 53, current learner rf
[flaml.automl.logger: 10-03 22:44:16] {3192} INFO -  at 12.3s,	estimator rf's best error=4.0882e-01,	best estimator rf's best error=4.0882e-01
[flaml.automl.logger: 10-03 22:44:16] {3006} INFO - iteration 54, current learner rf
[flaml.automl.logger: 10-03 22:44:16] {3192} INFO -  at 12.6s,	estimator rf's best error=4.0882e-01,	best estimator rf's best error=4.0882e-01
[flaml.automl.logger: 10-03 22:44:16] {3006} INFO - iteration 55, current learner rf
[flaml.automl.logger: 10-03 22:44:17] {3192} INFO -  at 12.8s,	estimator rf's best error=4.0882e-01,	best estimator rf's best error=4.0882e-01
[flaml.automl.logger: 10-03 22:44:17] {3006} INFO - iteration 56, current learner rf
[flaml.automl.logger: 10-03 22:44:17] {3192} INFO -  at 13.1s,	estimator rf's best error=4.0882e-01,	best estimator rf's best error=4.0882e-01
[flaml.automl.logger: 10-03 22:44:17] {3006} INFO - iteration 57, current learner rf
[flaml.automl.logger: 10-03 22:44:17] {3192} INFO -  at 13.4s,	estimator rf's best error=4.0882e-01,	best estimator rf's best error=4.0882e-01
[flaml.automl.logger: 10-03 22:44:17] {3006} INFO - iteration 58, current learner rf
[flaml.automl.logger: 10-03 22:44:17] {3192} INFO -  at 13.6s,	estimator rf's best error=4.0882e-01,	best estimator rf's best error=4.0882e-01
[flaml.automl.logger: 10-03 22:44:17] {3006} INFO - iteration 59, current learner rf
[flaml.automl.logger: 10-03 22:44:18] {3192} INFO -  at 13.9s,	estimator rf's best error=4.0882e-01,	best estimator rf's best error=4.0882e-01
[flaml.automl.logger: 10-03 22:44:18] {3006} INFO - iteration 60, current learner rf
[flaml.automl.logger: 10-03 22:44:18] {3192} INFO -  at 14.1s,	estimator rf's best error=4.0882e-01,	best estimator rf's best error=4.0882e-01
[flaml.automl.logger: 10-03 22:44:18] {3006} INFO - iteration 61, current learner rf
[flaml.automl.logger: 10-03 22:44:18] {3192} INFO -  at 14.4s,	estimator rf's best error=4.0882e-01,	best estimator rf's best error=4.0882e-01
[flaml.automl.logger: 10-03 22:44:18] {3006} INFO - iteration 62, current learner rf
[flaml.automl.logger: 10-03 22:44:19] {3192} INFO -  at 14.8s,	estimator rf's best error=4.0882e-01,	best estimator rf's best error=4.0882e-01
[flaml.automl.logger: 10-03 22:44:19] {3006} INFO - iteration 63, current learner rf
[flaml.automl.logger: 10-03 22:44:19] {3192} INFO -  at 15.0s,	estimator rf's best error=4.0882e-01,	best estimator rf's best error=4.0882e-01
[flaml.automl.logger: 10-03 22:44:19] {3006} INFO - iteration 64, current learner rf
[flaml.automl.logger: 10-03 22:44:19] {3192} INFO -  at 15.4s,	estimator rf's best error=4.0882e-01,	best estimator rf's best error=4.0882e-01
[flaml.automl.logger: 10-03 22:44:19] {3006} INFO - iteration 65, current learner rf
[flaml.automl.logger: 10-03 22:44:19] {3192} INFO -  at 15.6s,	estimator rf's best error=4.0882e-01,	best estimator rf's best error=4.0882e-01
[flaml.automl.logger: 10-03 22:44:19] {3006} INFO - iteration 66, current learner rf
[flaml.automl.logger: 10-03 22:44:20] {3192} INFO -  at 15.8s,	estimator rf's best error=4.0882e-01,	best estimator rf's best error=4.0882e-01
[flaml.automl.logger: 10-03 22:44:20] {3006} INFO - iteration 67, current learner rf
[flaml.automl.logger: 10-03 22:44:20] {3192} INFO -  at 16.1s,	estimator rf's best error=4.0882e-01,	best estimator rf's best error=4.0882e-01
[flaml.automl.logger: 10-03 22:44:20] {3006} INFO - iteration 68, current learner rf
[flaml.automl.logger: 10-03 22:44:20] {3192} INFO -  at 16.4s,	estimator rf's best error=4.0882e-01,	best estimator rf's best error=4.0882e-01
[flaml.automl.logger: 10-03 22:44:20] {3006} INFO - iteration 69, current learner rf
[flaml.automl.logger: 10-03 22:44:21] {3192} INFO -  at 16.7s,	estimator rf's best error=4.0882e-01,	best estimator rf's best error=4.0882e-01
[flaml.automl.logger: 10-03 22:44:21] {3006} INFO - iteration 70, current learner rf
[flaml.automl.logger: 10-03 22:44:21] {3192} INFO -  at 16.9s,	estimator rf's best error=4.0882e-01,	best estimator rf's best error=4.0882e-01
[flaml.automl.logger: 10-03 22:44:21] {3006} INFO - iteration 71, current learner rf
[flaml.automl.logger: 10-03 22:44:21] {3192} INFO -  at 17.3s,	estimator rf's best error=3.9831e-01,	best estimator rf's best error=3.9831e-01
[flaml.automl.logger: 10-03 22:44:21] {3006} INFO - iteration 72, current learner rf
[flaml.automl.logger: 10-03 22:44:21] {3192} INFO -  at 17.5s,	estimator rf's best error=3.9831e-01,	best estimator rf's best error=3.9831e-01
[flaml.automl.logger: 10-03 22:44:21] {3006} INFO - iteration 73, current learner rf
[flaml.automl.logger: 10-03 22:44:22] {3192} INFO -  at 17.9s,	estimator rf's best error=3.9831e-01,	best estimator rf's best error=3.9831e-01
[flaml.automl.logger: 10-03 22:44:22] {3006} INFO - iteration 74, current learner rf
[flaml.automl.logger: 10-03 22:44:22] {3192} INFO -  at 18.1s,	estimator rf's best error=3.9831e-01,	best estimator rf's best error=3.9831e-01
[flaml.automl.logger: 10-03 22:44:22] {3006} INFO - iteration 75, current learner rf
[flaml.automl.logger: 10-03 22:44:22] {3192} INFO -  at 18.4s,	estimator rf's best error=3.9831e-01,	best estimator rf's best error=3.9831e-01
[flaml.automl.logger: 10-03 22:44:22] {3006} INFO - iteration 76, current learner rf
[flaml.automl.logger: 10-03 22:44:22] {3192} INFO -  at 18.6s,	estimator rf's best error=3.9831e-01,	best estimator rf's best error=3.9831e-01
[flaml.automl.logger: 10-03 22:44:22] {3006} INFO - iteration 77, current learner rf
[flaml.automl.logger: 10-03 22:44:23] {3192} INFO -  at 19.0s,	estimator rf's best error=3.9831e-01,	best estimator rf's best error=3.9831e-01
[flaml.automl.logger: 10-03 22:44:23] {3006} INFO - iteration 78, current learner rf
[flaml.automl.logger: 10-03 22:44:23] {3192} INFO -  at 19.2s,	estimator rf's best error=3.9831e-01,	best estimator rf's best error=3.9831e-01
[flaml.automl.logger: 10-03 22:44:23] {3006} INFO - iteration 79, current learner rf
[flaml.automl.logger: 10-03 22:44:23] {3192} INFO -  at 19.6s,	estimator rf's best error=3.9831e-01,	best estimator rf's best error=3.9831e-01
[flaml.automl.logger: 10-03 22:44:23] {3006} INFO - iteration 80, current learner rf
[flaml.automl.logger: 10-03 22:44:24] {3192} INFO -  at 20.0s,	estimator rf's best error=3.9831e-01,	best estimator rf's best error=3.9831e-01
[flaml.automl.logger: 10-03 22:44:24] {3006} INFO - iteration 81, current learner rf
[flaml.automl.logger: 10-03 22:44:24] {3192} INFO -  at 20.2s,	estimator rf's best error=3.9831e-01,	best estimator rf's best error=3.9831e-01
[flaml.automl.logger: 10-03 22:44:24] {3006} INFO - iteration 82, current learner rf
[flaml.automl.logger: 10-03 22:44:24] {3192} INFO -  at 20.5s,	estimator rf's best error=3.9831e-01,	best estimator rf's best error=3.9831e-01
[flaml.automl.logger: 10-03 22:44:24] {3006} INFO - iteration 83, current learner rf
[flaml.automl.logger: 10-03 22:44:25] {3192} INFO -  at 20.9s,	estimator rf's best error=3.9831e-01,	best estimator rf's best error=3.9831e-01
[flaml.automl.logger: 10-03 22:44:25] {3006} INFO - iteration 84, current learner rf
[flaml.automl.logger: 10-03 22:44:25] {3192} INFO -  at 21.3s,	estimator rf's best error=3.9831e-01,	best estimator rf's best error=3.9831e-01

In [39]:
from sklearn.metrics import accuracy_score, f1_score

y_pred_automl = automl.predict(X_test_scaled)

automl_accuracy = accuracy_score(y_test, y_pred_automl)
automl_f1 = f1_score(y_test, y_pred_automl, average="macro")

print("Best AutoML model:", automl.best_estimator)
print("AutoML Accuracy:", automl_accuracy)
print("AutoML F1-score:", automl_f1)

Best AutoML model: rf
AutoML Accuracy: 0.84375
AutoML F1-score: 0.5072505521943724

### **Insights**: 

The manually trained Random Forest performed best, with 88.4% accuracy and a 54.4% F1-score, compared with Logistic Regression (84.4%, 46.8%) and FLAML AutoML (84.4%, 50.7%). Random Forest likely performed better because it can capture nonlinear relationships and interactions among wine characteristics. FLAML also selected Random Forest as its best estimator, supporting its suitability for this dataset. Overall, the manually trained Random Forest showed the best performance.